Repository larien/learn-go-with-tests, pull requests merged in 2019-12, with the labels that each got.

#75 Traducao/ola mundo
  README.md
  SUMMARY.md
  build.books.sh
  build.sh
  go.mod
  go.sum
  hello-world/v2/hello.go
  hello-world/v2/hello_test.go
  hello-world/v3/hello.go
  hello-world/v3/hello_test.go
  hello-world/v4/hello.go
  hello-world/v4/hello_test.go
  hello-world/v5/hello.go
  hello-world/v5/hello_test.go
  hello-world/v6/hello.go
  hello-world/v6/hello_test.go
  hello-world/v7/hello.go
  hello-world/v7/hello_test.go
  hello-world/v8/hello.go
  hello-world/v8/hello_test.go
  meta/contribuindo.md
  mocks/v5/main.go
  ola-mundo/v1/ola.go
  ola-mundo/v2/ola.go
  ola-mundo/v2/ola_test.go
  ola-mundo/v3/ola.go
  ola-mundo/v3/ola_test.go
  ola-mundo/v4/ola.go
  ola-mundo/v4/ola_test.go
  ola-mundo/v5/ola.go
  ola-mundo/v5/ola_test.go
  ola-mundo/v6/ola.go
  ola-mundo/v6/ola_test.go
  ola-mundo/v7/ola.go
  ola-mundo/v7/ola_test.go
  ola-mundo/v8/ola.go
  ola-mundo/v8/ola_test.go
  primeiros-passos-com-go/hello-world.md
  primeiros-passos-com-go/injecao-de-dependencia.md
  primeiros-passos-com-go/inteiros.md
  primeiros-passos-com-go/ola-mundo.md
Labels: tradução

#73 adiciona conteúdo instalar Go no Windows
  primeiros-passos-com-go/instalacao-do-go.md
Labels: conteúdo novo, precisando de revisão

#55 Ponteiros e erros
  README.md
  SUMMARY.md
  build.books.sh
  pointers/v1/wallet.go
  pointers/v1/wallet_test.go
  pointers/v2/wallet.go
  pointers/v2/wallet_test.go
  pointers/v3/wallet.go
  pointers/v3/wallet_test.go
  pointers/v4/wallet.go
  pointers/v4/wallet_test.go
  ponteiros/v1/carteira.go
  ponteiros/v1/carteira_test.go
  ponteiros/v2/carteira.go
  ponteiros/v2/carteira_test.go
  ponteiros/v3/carteira.go
  ponteiros/v3/carteira_test.go
  ponteiros/v4/carteira.go
  ponteiros/v4/carteira_test.go
  primeiros-passos-com-go/pointers-and-errors.md
  primeiros-passos-com-go/ponteiros-e-erros.md
Labels: precisando de revisão, tradução

#69 Traducao/select
  primeiros-passos-com-go/mocks.md
  primeiros-passos-com-go/select.md
  select/v1/corredor.go
  select/v1/corredor_test.go
  select/v1/racer.go
  select/v1/racer_test.go
  select/v2/corredor.go
  select/v2/corredor_test.go
  select/v2/racer.go
  select/v2/racer_test.go
  select/v3/corredor.go
  select/v3/corredor_test.go
  select/v3/racer.go
  select/v3/racer_test.go
Labels: precisando de revisão, tradução

#61 Traducao/sync
  primeiros-passos-com-go/sync.md
  sync/v1/sync.go
  sync/v1/sync_test.go
  sync/v2/sync.go
  sync/v2/sync_test.go
Labels: precisando de revisão, tradução

#67 Tradução do capítulo referente ao context
  context/v1/context.go
  context/v1/context_test.go
  context/v2/context.go
  context/v2/context_test.go
  context/v2/testdoubles.go
  context/v3/context.go
  context/v3/context_test.go
  context/v3/testdoubles.go
  primeiros-passos-com-go/context.md
Labels: precisando de revisão, tradução
