Repository larien/learn-go-with-tests, pull requests merged in 2019-10, with the labels that each got.

#60 Remove English reference
  README.md
Labels: documentation

#54 Tradução de "11. Concorrência"
  README.md
  SUMMARY.md
  build.books.sh
  concorrencia/v1/VerificaWebsite.go
  concorrencia/v1/VerificaWebsites.go
  concorrencia/v1/VerificaWebsites_benchmark_test.go
  concorrencia/v1/VerificaWebsites_test.go
  concorrencia/v2/VerificaWebsite.go
  concorrencia/v2/VerificaWebsites.go
  concorrencia/v2/VerificaWebsites_benchmark_test.go
  concorrencia/v2/VerificaWebsites_test.go
  concorrencia/v3/VerificaWebsite.go
  concorrencia/v3/VerificaWebsites.go
  concorrencia/v3/VerificaWebsites_benchmark_test.go
  concorrencia/v3/VerificaWebsites_test.go
  concurrency/v1/CheckWebsite.go
  concurrency/v1/CheckWebsites.go
  concurrency/v1/CheckWebsites_benchmark_test.go
  concurrency/v2/CheckWebsite.go
  concurrency/v2/CheckWebsites.go
  concurrency/v2/CheckWebsites_benchmark_test.go
  concurrency/v3/CheckWebsite.go
  concurrency/v3/CheckWebsites.go
  concurrency/v3/CheckWebsites_benchmark_test.go
  go.mod
  primeiros-passos-com-go/concorrencia.md
  primeiros-passos-com-go/concurrency.md
  primeiros-passos-com-go/sync.md
Labels: hacktoberfest, tradução

#70 Revisao 3.Inteiros
  inteiros/v2/adicionador_test.go
  primeiros-passos-com-go/inteiros.md
Labels: precisando de revisão, revisão
